# Generated by go generate.
# Set ARIN_API_KEY in the environment.
# This data source stores sensitive content in Terraform state.
data "arin_ticket_summaries" "example" {
  ticket_type   = "ANY"
  ticket_status = "ANY_OPEN"
}
