# Generated by go generate.
# Set ARIN_API_KEY in the environment.
# This data source stores sensitive content in Terraform state.
data "arin_ticket_summary" "example" {
  ticket_number = "20260922-X1"
}
