# Generated by go generate.
# Set ARIN_API_KEY in the environment.
# This data source stores sensitive content in Terraform state.
data "arin_ticket" "example" {
  ticket_number           = "20260922-X1"
  message_references_only = true
}
