package provider

import (
	"context"
	"fmt"

	"github.com/as19814/terraform-provider-arin/internal/arin"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource                   = &autnumResource{}
	_ resource.ResourceWithConfigure      = &autnumResource{}
	_ resource.ResourceWithImportState    = &autnumResource{}
	_ resource.ResourceWithValidateConfig = &autnumResource{}
)

type autnumResource struct{ client *arin.Client }
type autnumModel struct {
	Source          types.String `tfsdk:"source"`
	ImportPolicy    types.List   `tfsdk:"import_policy"`
	ExportPolicy    types.List   `tfsdk:"export_policy"`
	DefaultPolicy   types.List   `tfsdk:"default_policy"`
	MPImportPolicy  types.List   `tfsdk:"mp_import_policy"`
	MPExportPolicy  types.List   `tfsdk:"mp_export_policy"`
	MPDefaultPolicy types.List   `tfsdk:"mp_default_policy"`

	ID               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"as_number"`
	ASName           types.String `tfsdk:"as_name"`
	OrgHandle        types.String `tfsdk:"org_handle"`
	Description      types.List   `tfsdk:"description"`
	Remarks          types.List   `tfsdk:"remarks"`
	MemberOf         types.Set    `tfsdk:"member_of"`
	POCs             types.Set    `tfsdk:"poc_links"`
	CreationDate     types.String `tfsdk:"creation_date"`
	LastModifiedDate types.String `tfsdk:"last_modified_date"`
}

func NewAutnumResource() resource.Resource { return &autnumResource{} }
func (r *autnumResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_irr_aut_num"
}
func (r *autnumResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage a simple (XML) ARIN IRR aut-num. Owns its name, description, remarks, routing policies, and AS-set membership. This IRR object is separate from the ASN registration. POC links are generated by ARIN from the organization. Advanced RPSL objects are not supported. Import existing IRR aut-num objects by ASN before managing them. Removing this resource from configuration deletes the aut-num from ARIN. The lifecycle is tested against a fake server and OT&E; production writes have not been validated.",
		Attributes: map[string]schema.Attribute{
			"source":            schema.StringAttribute{Computed: true, MarkdownDescription: "IRR source returned by ARIN."},
			"id":                schema.StringAttribute{Computed: true, MarkdownDescription: "Canonical ASN such as AS64496, also used as the import ID.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"as_number":         schema.StringAttribute{Required: true, MarkdownDescription: "Canonical ASN such as AS64496. Changing it requires replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"org_handle":        schema.StringAttribute{Required: true, MarkdownDescription: "Uppercase maintaining organization handle. Changing it replaces the object.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description":       schema.ListAttribute{Required: true, ElementType: types.StringType, MarkdownDescription: "Ordered description lines, at least one. Each entry is one nonempty line without surrounding whitespace."},
			"remarks":           schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered remarks lines. Defaults to empty; omission clears existing remarks on apply."},
			"as_name":           schema.StringAttribute{Required: true, MarkdownDescription: "Alphanumeric IRR AS name with optional hyphens."},
			"member_of":         schema.SetAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: setdefault.StaticValue(types.SetValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "AS sets containing this aut-num. Defaults to empty; omission clears membership."},
			"import_policy":     schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered RPSL import policy lines. Omission clears this policy."},
			"export_policy":     schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered RPSL export policy lines. Omission clears this policy."},
			"default_policy":    schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered RPSL default policy lines. Omission clears this policy."},
			"mp_import_policy":  schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered RPSL mp-import policy lines. Omission clears this policy."},
			"mp_export_policy":  schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered RPSL mp-export policy lines. Omission clears this policy."},
			"mp_default_policy": schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered RPSL mp-default policy lines. Omission clears this policy."},

			"poc_links": schema.SetNestedAttribute{Computed: true, MarkdownDescription: "POC links generated by ARIN from the maintaining organization. These cannot be configured or changed on the aut-num.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"handle":      schema.StringAttribute{Computed: true, MarkdownDescription: "POC handle returned by ARIN."},
				"function":    schema.StringAttribute{Computed: true, MarkdownDescription: "POC role returned by ARIN."},
				"description": schema.StringAttribute{Computed: true, MarkdownDescription: "POC role description returned by ARIN."},
			}}},
			"creation_date":      schema.StringAttribute{Computed: true, MarkdownDescription: "Creation timestamp reported by ARIN, or null when absent."},
			"last_modified_date": schema.StringAttribute{Computed: true, MarkdownDescription: "Last modification timestamp reported by ARIN, or null when absent."},
		},
	}
}
func (r *autnumResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*arin.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider configuration", fmt.Sprintf("Expected *arin.Client, got %T", req.ProviderData))
		return
	}
	r.client = client
}
func (m autnumModel) api(ctx context.Context) (arin.Autnum, diag.Diagnostics) {
	s := arin.Autnum{Name: m.Name.ValueString(), ASName: m.ASName.ValueString(), OrgHandle: m.OrgHandle.ValueString()}
	var d diag.Diagnostics
	d.Append(m.Description.ElementsAs(ctx, &s.Description, false)...)
	d.Append(m.Remarks.ElementsAs(ctx, &s.Remarks, false)...)
	d.Append(m.MemberOf.ElementsAs(ctx, &s.MemberOf, false)...)
	d.Append(m.ImportPolicy.ElementsAs(ctx, &s.ImportPolicy, false)...)
	d.Append(m.ExportPolicy.ElementsAs(ctx, &s.ExportPolicy, false)...)
	d.Append(m.DefaultPolicy.ElementsAs(ctx, &s.DefaultPolicy, false)...)
	d.Append(m.MPImportPolicy.ElementsAs(ctx, &s.MPImportPolicy, false)...)
	d.Append(m.MPExportPolicy.ElementsAs(ctx, &s.MPExportPolicy, false)...)
	d.Append(m.MPDefaultPolicy.ElementsAs(ctx, &s.MPDefaultPolicy, false)...)

	return s, d
}
func (r *autnumResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var m autnumModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Unknown expressions are validated after Terraform resolves the plan.
	for _, v := range []attr.Value{m.Name, m.ASName, m.OrgHandle, m.Description, m.Remarks, m.MemberOf, m.ImportPolicy, m.ExportPolicy, m.DefaultPolicy, m.MPImportPolicy, m.MPExportPolicy, m.MPDefaultPolicy} {
		tv, err := v.ToTerraformValue(ctx)
		if err != nil || !tv.IsFullyKnown() {
			return
		}
	}
	s, d := m.api(ctx)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		if err := s.Validate(); err != nil {
			resp.Diagnostics.AddError("Invalid aut-num configuration", err.Error())
		}
	}
}
func autnumState(ctx context.Context, s *arin.Autnum) (autnumModel, diag.Diagnostics) {
	m := autnumModel{Source: types.StringValue("ARIN"), ID: types.StringValue(s.Name), Name: types.StringValue(s.Name), ASName: types.StringValue(s.ASName), OrgHandle: types.StringValue(s.OrgHandle), CreationDate: types.StringNull(), LastModifiedDate: types.StringNull()}
	if s.CreationDate != "" {
		m.CreationDate = types.StringValue(s.CreationDate)
	}
	if s.LastModifiedDate != "" {
		m.LastModifiedDate = types.StringValue(s.LastModifiedDate)
	}
	var d, next diag.Diagnostics
	m.Description, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.Description))
	d.Append(next...)
	m.Remarks, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.Remarks))
	d.Append(next...)
	m.MemberOf, next = types.SetValueFrom(ctx, types.StringType, nonNilStrings(s.MemberOf))
	d.Append(next...)
	m.ImportPolicy, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.ImportPolicy))
	d.Append(next...)
	m.ExportPolicy, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.ExportPolicy))
	d.Append(next...)
	m.DefaultPolicy, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.DefaultPolicy))
	d.Append(next...)
	m.MPImportPolicy, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.MPImportPolicy))
	d.Append(next...)
	m.MPExportPolicy, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.MPExportPolicy))
	d.Append(next...)
	m.MPDefaultPolicy, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.MPDefaultPolicy))
	d.Append(next...)

	pocs := []irrPOCResponseModel{}
	for _, p := range s.POCs {
		pocs = append(pocs, irrPOCResponseModel{Handle: types.StringValue(p.Handle), Function: types.StringValue(p.Function), Description: types.StringValue(p.Description)})
	}
	m.POCs, next = types.SetValueFrom(ctx, irrPOCResponseType, pocs)
	d.Append(next...)
	return m, d
}
func (r *autnumResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var m autnumModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	s, d := m.api(ctx)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := r.client.CreateAutnum(ctx, s)
	if err != nil {
		resp.Diagnostics.AddError("Could not create aut-num", err.Error()+". If a write was sent, verify the object before retrying; import it by name if creation succeeded.")
		return
	}
	m, d = autnumState(ctx, result)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
	}
}
func (r *autnumResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var m autnumModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := r.client.GetAutnum(ctx, m.ID.ValueString())
	if arin.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Could not read aut-num", err.Error())
		return
	}
	m, d := autnumState(ctx, result)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
	}
}
func (r *autnumResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var m autnumModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	s, d := m.api(ctx)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := r.client.UpdateAutnum(ctx, s)
	if err != nil {
		resp.Diagnostics.AddError("Could not update aut-num", err.Error()+". Refresh the object before retrying an uncertain write.")
		return
	}
	m, d = autnumState(ctx, result)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
	}
}
func (r *autnumResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var m autnumModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteAutnum(ctx, m.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Could not delete aut-num", err.Error()+". Refresh the object before retrying an uncertain write.")
	}
}
func (r *autnumResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if err := arin.ValidateAutnumName(req.ID); err != nil {
		resp.Diagnostics.AddError("Invalid aut-num import ID", err.Error())
		return
	}
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
