package provider

import (
	"context"
	"fmt"

	"github.com/as19814/terraform-provider-arin/internal/arin"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource                   = &irrRouteResource{}
	_ resource.ResourceWithConfigure      = &irrRouteResource{}
	_ resource.ResourceWithImportState    = &irrRouteResource{}
	_ resource.ResourceWithValidateConfig = &irrRouteResource{}
)

type irrRouteResource struct{ client *arin.Client }
type irrRouteModel struct {
	ID               types.String `tfsdk:"id"`
	Prefix           types.String `tfsdk:"prefix"`
	OriginAS         types.String `tfsdk:"origin_as"`
	NetHandle        types.String `tfsdk:"net_handle"`
	OrgHandle        types.String `tfsdk:"org_handle"`
	Description      types.List   `tfsdk:"description"`
	Remarks          types.List   `tfsdk:"remarks"`
	POCs             types.Set    `tfsdk:"poc_links"`
	CreationDate     types.String `tfsdk:"creation_date"`
	LastModifiedDate types.String `tfsdk:"last_modified_date"`
}

func NewIRRRouteResource() resource.Resource { return &irrRouteResource{} }
func (r *irrRouteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_irr_route"
}
func (r *irrRouteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage a simple IPv4 or IPv6 ARIN IRR route. Prefix and origin ASN identify the object; changing either requires replacement. Owns description and remarks. POC links and network handle are generated by ARIN. Advanced RPSL routes, memberOf associations, and ROA-linked routes are not supported. Removing the resource deletes the route. Import existing routes by prefix and origin ASN separated by a comma.",
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true, MarkdownDescription: "Canonical prefix and origin ASN separated by a comma, for example 192.0.2.0/24,AS64496. Also used as the import ID.", PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()}},
			"prefix":      schema.StringAttribute{Required: true, MarkdownDescription: "Canonical IPv4 or IPv6 network CIDR. Host bits must be zero. Changes require replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"origin_as":   schema.StringAttribute{Required: true, MarkdownDescription: "Canonical origin ASN, such as AS64496. Changes require replacement.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"net_handle":  schema.StringAttribute{Computed: true, MarkdownDescription: "Network registration handle assigned by ARIN."},
			"org_handle":  schema.StringAttribute{Required: true, MarkdownDescription: "Uppercase maintaining organization handle. Changing it replaces the object.", PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()}},
			"description": schema.ListAttribute{Required: true, ElementType: types.StringType, MarkdownDescription: "Ordered description lines, at least one. Each entry is one nonempty line without surrounding whitespace."},
			"remarks":     schema.ListAttribute{Optional: true, Computed: true, ElementType: types.StringType, Default: listdefault.StaticValue(types.ListValueMust(types.StringType, []attr.Value{})), MarkdownDescription: "Ordered remarks lines. Defaults to empty; omission clears existing remarks on apply."},
			"poc_links": schema.SetNestedAttribute{Computed: true, MarkdownDescription: "POC links generated by ARIN from the maintaining organization. These cannot be configured or changed on the IRR route.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
				"handle":   schema.StringAttribute{Computed: true, MarkdownDescription: "POC handle returned by ARIN."},
				"function": schema.StringAttribute{Computed: true, MarkdownDescription: "POC role returned by ARIN."},
			}}},
			"creation_date":      schema.StringAttribute{Computed: true, MarkdownDescription: "Creation timestamp reported by ARIN, or null when absent."},
			"last_modified_date": schema.StringAttribute{Computed: true, MarkdownDescription: "Last modification timestamp reported by ARIN, or null when absent."},
		},
	}
}
func (r *irrRouteResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*arin.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider configuration", fmt.Sprintf("Expected *arin.Client, got %T", req.ProviderData))
		return
	}
	r.client = client
}
func (m irrRouteModel) api(ctx context.Context) (arin.IRRRoute, diag.Diagnostics) {
	s := arin.IRRRoute{Prefix: m.Prefix.ValueString(), OriginAS: m.OriginAS.ValueString(), OrgHandle: m.OrgHandle.ValueString()}
	var d diag.Diagnostics
	d.Append(m.Description.ElementsAs(ctx, &s.Description, false)...)
	d.Append(m.Remarks.ElementsAs(ctx, &s.Remarks, false)...)

	return s, d
}
func (r *irrRouteResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var m irrRouteModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Unknown expressions are validated after Terraform resolves the plan.
	for _, v := range []attr.Value{m.Prefix, m.OriginAS, m.OrgHandle, m.Description, m.Remarks} {
		tv, err := v.ToTerraformValue(ctx)
		if err != nil || !tv.IsFullyKnown() {
			return
		}
	}
	s, d := m.api(ctx)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		if err := s.Validate(); err != nil {
			resp.Diagnostics.AddError("Invalid IRR route configuration", err.Error())
		}
	}
}
func irrRouteState(ctx context.Context, s *arin.IRRRoute) (irrRouteModel, diag.Diagnostics) {
	m := irrRouteModel{ID: types.StringValue(s.ID()), Prefix: types.StringValue(s.Prefix), OriginAS: types.StringValue(s.OriginAS), NetHandle: types.StringValue(s.NetHandle), OrgHandle: types.StringValue(s.OrgHandle), CreationDate: types.StringNull(), LastModifiedDate: types.StringNull()}
	if s.CreationDate != "" {
		m.CreationDate = types.StringValue(s.CreationDate)
	}
	if s.LastModifiedDate != "" {
		m.LastModifiedDate = types.StringValue(s.LastModifiedDate)
	}
	var d, next diag.Diagnostics
	m.Description, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.Description))
	d.Append(next...)
	m.Remarks, next = types.ListValueFrom(ctx, types.StringType, nonNilStrings(s.Remarks))
	d.Append(next...)
	pocs := []irrPOCModel{}
	for _, p := range s.POCs {
		pocs = append(pocs, irrPOCModel{types.StringValue(p.Handle), types.StringValue(p.Function)})
	}
	m.POCs, next = types.SetValueFrom(ctx, irrPOCType, pocs)
	d.Append(next...)
	return m, d
}
func (r *irrRouteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var m irrRouteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	s, d := m.api(ctx)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := r.client.CreateIRRRoute(ctx, s)
	if err != nil {
		resp.Diagnostics.AddError("Could not create IRR route", err.Error()+". If a write was sent, verify the object before retrying; import it by CIDR,AS<number> if creation succeeded.")
		return
	}
	m, d = irrRouteState(ctx, result)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
	}
}
func (r *irrRouteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var m irrRouteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := r.client.GetIRRRoute(ctx, m.ID.ValueString())
	if arin.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Could not read IRR route", err.Error())
		return
	}
	if err := result.CheckManaged(); err != nil {
		resp.Diagnostics.AddError("Unsupported IRR route", err.Error())
		return
	}
	m, d := irrRouteState(ctx, result)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
	}
}
func (r *irrRouteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var m irrRouteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	s, d := m.api(ctx)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	result, err := r.client.UpdateIRRRoute(ctx, s)
	if err != nil {
		resp.Diagnostics.AddError("Could not update IRR route", err.Error()+". Refresh the object before retrying an uncertain write.")
		return
	}
	m, d = irrRouteState(ctx, result)
	resp.Diagnostics.Append(d...)
	if !resp.Diagnostics.HasError() {
		resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
	}
}
func (r *irrRouteResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var m irrRouteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteIRRRoute(ctx, m.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Could not delete IRR route", err.Error()+". Refresh the object before retrying an uncertain write.")
	}
}
func (r *irrRouteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if err := arin.ValidateIRRRouteID(req.ID); err != nil {
		resp.Diagnostics.AddError("Invalid IRR route import ID", err.Error())
		return
	}
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
