// Command catalog generates examples and the supported data source index.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/as19814/terraform-provider-arin/internal/arin"
)

func main() {
	specs := append(arin.RegistrationReads(), arin.PublicReads()...)
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
	index := `# Data source coverage

All non-report read endpoints documented in the collected Reg-RWS, IRR, and hosted RPKI guides have data sources. Public RDAP also supplies network and ASN discovery, ASN registration details, and organization contact references.

Report-request endpoints are intentionally excluded: they create tickets even though ARIN exposes them as HTTP GET. These data sources perform no write operations; managed resources are documented separately. Historical Whois-RWS search variations, delegated RPKI protocol exchanges, and account report-generation workflows are not Terraform data sources in this provider.

## Catalog

| Data source | API | Purpose |
| --- | --- | --- |
| [arin_networks](../data-sources/networks.md) | Public RDAP | Discover networks directly registered to an organization. |
`
	for _, spec := range specs {
		dir := filepath.Join("examples", "data-sources", "arin_"+spec.Name)
		must(os.MkdirAll(dir, 0755))
		example := "# Generated by go generate.\n"
		if !spec.Public {
			example += "# Set ARIN_API_KEY in the environment.\n"
		}
		if spec.Sensitive {
			example += "# This data source stores sensitive content in Terraform state.\n"
		}
		example += fmt.Sprintf("data %q %q {\n", "arin_"+spec.Name, "example")
		for _, in := range spec.Inputs {
			value := fmt.Sprintf("%q", in.Example)
			if in.Kind == "asn" || in.Kind == "id" || in.Kind == "bool" {
				value = in.Example
			}
			example += fmt.Sprintf("  %s = %s\n", in.Name, value)
		}
		example += "}\n"
		must(os.WriteFile(filepath.Join(dir, "data-source.tf"), []byte(example), 0644))
		api := "Reg-RWS"
		if spec.Public {
			api = "Public RDAP"
		} else if strings.HasPrefix(spec.Name, "irr_") || spec.Name == "net_routes" {
			api = "IRR"
		} else if strings.HasPrefix(spec.Name, "roa") || strings.HasPrefix(spec.Name, "aspa") {
			api = "Hosted RPKI"
		}
		index += fmt.Sprintf("| [arin_%s](../data-sources/%s.md) | %s | %s |\n", spec.Name, spec.Name, api, spec.Description)
	}
	index += `
## Behavior

- Individual lookups return errors for missing records. Collection lookups return empty lists for successful empty collections, never for authentication errors.
- Public RDAP searches reject truncation and pagination rather than returning an incomplete inventory.
- Registration collections reject unexpected record types. No response-provided links are followed.
- IP addresses are normalized, including ARIN's decimal, zero-padded IPv4 format. Optional server fields remain null. Ordered text follows numeric line indices.
- API keys are used only for authenticated registration reads. Public RDAP requests do not carry them.
- Customer and ticket content, attachments, and organization tax IDs are sensitive in Terraform's UI. Sensitive values are still stored in state.
- Attachments remain in memory and are returned as base64, with filename, content type, byte count, and SHA-256. No files are written; the 4 MiB response limit applies.
- Collection-only RPKI APIs are used for individual ROA/ASPA selection. Reads never synthesize RPKI objects.

## Testing and API notes

Mock acceptance tests cover every catalog entry through real Terraform, including typed nested values, identity checks, errors, empty inventories, and refresh. Fixtures use documentation address ranges and synthetic contact/customer/ticket data.

The opt-in live suite follows existing records from the selected organization. Network, contact, ASN, IRR, ROA, and ASPA reads were exercised against FT-684. Live customer, individual aut-num/route-set, and ticket-content reads require suitable existing records; mock coverage does not imply live verification of those cases.

The ASPA endpoint requires Content-Type: application/xml even on GET. The client supplies it for authenticated reads.

ARIN's current "Get Ticket Payload List" header-auth example repeats the single-ticket summary URL. The implemented listing path uses the matrix-filter endpoint documented in the adjacent URL-auth example, with authentication moved to the header. No key is placed in the URL. Both filtered ticket-list endpoints were also checked live and returned valid empty collections for open QUESTION tickets.

The provider does not promise that every account can access every object. Authorization errors are reported without falling back to a different account or service.
`
	must(os.WriteFile("docs/reference/data-sources.md", []byte(index), 0644))
}
func must(err error) {
	if err != nil {
		panic(err)
	}
}
